name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - stable
      - v*

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # This is the "main" test suite, which tests a large number of different
  # versions of default compilers and Python versions in GitHub Actions.
  standard:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-2022', 'macos-latest']
        python: ['3.8', '3.9', '3.10', '3.11', '3.12.0-alpha.4', 'pypy3.9']
        exclude:
          - os: 'macos-latest'
            python: 'pypy3.9'
          - os: 'windows-2022'
            python: '3.12.0-alpha.4'

    name: "Python ${{ matrix.python }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Update CMake
      uses: jwlawson/actions-setup-cmake@v1.13

    - name: Install Eigen
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get -y install libeigen3-dev

    - name: Install PyTest
      run: |
        python -m pip install pytest pytest-github-actions-annotate-failures

    - name: Install NumPy
      if: matrix.python != 'pypy3.9' && matrix.python != '3.12.0-alpha.4'
      run: |
        python -m pip install numpy

    - name: Configure
      run: >
        cmake -S . -B build "-DPython_EXECUTABLE=$(python3 -c 'import sys; print(sys.executable)')" -DNB_TEST_STABLE_ABI=ON

    - name: Build C++
      run: cmake --build build -j 2

    - name: Run tests
      run: >
        cd build;
        python -m pytest
